# Nombre del proyecto
#sonar.projectKey=sumativa3-frontend
sonar.projectKey=sumativa3-frontend
sonar.projectName=Sumativa3 Frontend
sonar.projectVersion=1.0

# Ruta del código fuente
sonar.sources=src
sonar.inclusions=**/*.ts,**/*.html

# Lenguaje
sonar.language=ts

# Exclusiones (opcional)
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.css,**/*.scss

# Configura tu servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación
sonar.login=sqp_b4bed15b80d782ffd2384dbb1d781ea42bb463d1
#sonar.token=28e48387759761f617ddd33ca75a3caa17cd5c8c

#Cobertura de tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info